const RoomActionTypes = {
	SET_ROOM_DATA: 'SET_ROOM_DATA',
	TOGGLE_EMOJI_POPUP: 'TOGGLE_EMOJI_POPUP',
	TOGGLE_CODE_POPUP: 'TOGGLE_CODE_POPUP',
	SET_THEME: 'SET_THEME',
	SET_LANGUAGE: 'SET_LANGUAGE'
};

export default RoomActionTypes;